name: Windows build and test with Conda

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test-win:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare conda environment
      shell: cmd
      run: |
        rem Note: Conda VC setenv-script works only with cmd on Win
        rem Source conda hook
        set CONDA=C:\Miniconda
        call %CONDA%\condabin\conda_hook.bat
        call conda create -n mstruct-env -y -c conda-forge python=3.6 libblas=*=*mkl boost=1.66 lapack fftw gsl scons bzip2 git vs2019_win-64 
    - name: Build MStruct
      shell: cmd
      run: |
        set CONDA=C:\Miniconda
        call %CONDA%\condabin\conda_hook.bat
        call conda activate mstruct-env
        rem Get conda env prefix
        call conda info --json | grep default_prefix > _tmp_path1.txt
        (for /f tokens^=3^,4^,*^ delims^=^" %%a in (_tmp_path1.txt) do echo %%b) > _tmp_path2.txt
        for /f "usebackq tokens=*" %%i in (`cat _tmp_path2.txt`) do (
          set P=%%i
        )
        set P=%P:\\=\%
        echo conda_prefix: %P%
        rem Set CPP env variables
        set CPPPATH=%P%\Library\include;%P%\include
        set LIBRARY_PATH=%P%\Library\lib;%P%\libs
        cd libmstruct
        call scons -j4 install prefix=%P%/Library modulepath=%P%/Lib/site-packages
    - name: Test MStruct
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate mstruct
        P="$(conda info --json | grep default_prefix | cut -d\" -f4)"
        export LD_LIBRARY_PATH=$P/lib
        mstruct -v
        ldd $(which mstruct)
    - name: Make distribution
      shell: bash
      run: |
        mkdir -p dist
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
